# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/notfatnotfunny/Gadgetbridge/tools/mi-band10-gtk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/notfatnotfunny/Gadgetbridge/tools/mi-band10-gtk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/notfatnotfunny/Gadgetbridge/tools/mi-band10-gtk/CMakeFiles /home/notfatnotfunny/Gadgetbridge/tools/mi-band10-gtk//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/notfatnotfunny/Gadgetbridge/tools/mi-band10-gtk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mi-band10-viewer

# Build rule for target.
mi-band10-viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mi-band10-viewer
.PHONY : mi-band10-viewer

# fast build rule for target.
mi-band10-viewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/build
.PHONY : mi-band10-viewer/fast

src/gb_db.o: src/gb_db.c.o
.PHONY : src/gb_db.o

# target to build an object file
src/gb_db.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/gb_db.c.o
.PHONY : src/gb_db.c.o

src/gb_db.i: src/gb_db.c.i
.PHONY : src/gb_db.i

# target to preprocess a source file
src/gb_db.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/gb_db.c.i
.PHONY : src/gb_db.c.i

src/gb_db.s: src/gb_db.c.s
.PHONY : src/gb_db.s

# target to generate assembly for a file
src/gb_db.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/gb_db.c.s
.PHONY : src/gb_db.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/main.c.s
.PHONY : src/main.c.s

src/mib10_activity.o: src/mib10_activity.c.o
.PHONY : src/mib10_activity.o

# target to build an object file
src/mib10_activity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_activity.c.o
.PHONY : src/mib10_activity.c.o

src/mib10_activity.i: src/mib10_activity.c.i
.PHONY : src/mib10_activity.i

# target to preprocess a source file
src/mib10_activity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_activity.c.i
.PHONY : src/mib10_activity.c.i

src/mib10_activity.s: src/mib10_activity.c.s
.PHONY : src/mib10_activity.s

# target to generate assembly for a file
src/mib10_activity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_activity.c.s
.PHONY : src/mib10_activity.c.s

src/mib10_bluez.o: src/mib10_bluez.c.o
.PHONY : src/mib10_bluez.o

# target to build an object file
src/mib10_bluez.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_bluez.c.o
.PHONY : src/mib10_bluez.c.o

src/mib10_bluez.i: src/mib10_bluez.c.i
.PHONY : src/mib10_bluez.i

# target to preprocess a source file
src/mib10_bluez.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_bluez.c.i
.PHONY : src/mib10_bluez.c.i

src/mib10_bluez.s: src/mib10_bluez.c.s
.PHONY : src/mib10_bluez.s

# target to generate assembly for a file
src/mib10_bluez.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_bluez.c.s
.PHONY : src/mib10_bluez.c.s

src/mib10_crypto.o: src/mib10_crypto.c.o
.PHONY : src/mib10_crypto.o

# target to build an object file
src/mib10_crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_crypto.c.o
.PHONY : src/mib10_crypto.c.o

src/mib10_crypto.i: src/mib10_crypto.c.i
.PHONY : src/mib10_crypto.i

# target to preprocess a source file
src/mib10_crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_crypto.c.i
.PHONY : src/mib10_crypto.c.i

src/mib10_crypto.s: src/mib10_crypto.c.s
.PHONY : src/mib10_crypto.s

# target to generate assembly for a file
src/mib10_crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_crypto.c.s
.PHONY : src/mib10_crypto.c.s

src/mib10_ui.o: src/mib10_ui.c.o
.PHONY : src/mib10_ui.o

# target to build an object file
src/mib10_ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_ui.c.o
.PHONY : src/mib10_ui.c.o

src/mib10_ui.i: src/mib10_ui.c.i
.PHONY : src/mib10_ui.i

# target to preprocess a source file
src/mib10_ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_ui.c.i
.PHONY : src/mib10_ui.c.i

src/mib10_ui.s: src/mib10_ui.c.s
.PHONY : src/mib10_ui.s

# target to generate assembly for a file
src/mib10_ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_ui.c.s
.PHONY : src/mib10_ui.c.s

src/mib10_wire.o: src/mib10_wire.c.o
.PHONY : src/mib10_wire.o

# target to build an object file
src/mib10_wire.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_wire.c.o
.PHONY : src/mib10_wire.c.o

src/mib10_wire.i: src/mib10_wire.c.i
.PHONY : src/mib10_wire.i

# target to preprocess a source file
src/mib10_wire.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_wire.c.i
.PHONY : src/mib10_wire.c.i

src/mib10_wire.s: src/mib10_wire.c.s
.PHONY : src/mib10_wire.s

# target to generate assembly for a file
src/mib10_wire.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/mib10_wire.c.s
.PHONY : src/mib10_wire.c.s

src/xiaomi.pb-c.o: src/xiaomi.pb-c.c.o
.PHONY : src/xiaomi.pb-c.o

# target to build an object file
src/xiaomi.pb-c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/xiaomi.pb-c.c.o
.PHONY : src/xiaomi.pb-c.c.o

src/xiaomi.pb-c.i: src/xiaomi.pb-c.c.i
.PHONY : src/xiaomi.pb-c.i

# target to preprocess a source file
src/xiaomi.pb-c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/xiaomi.pb-c.c.i
.PHONY : src/xiaomi.pb-c.c.i

src/xiaomi.pb-c.s: src/xiaomi.pb-c.c.s
.PHONY : src/xiaomi.pb-c.s

# target to generate assembly for a file
src/xiaomi.pb-c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mi-band10-viewer.dir/build.make CMakeFiles/mi-band10-viewer.dir/src/xiaomi.pb-c.c.s
.PHONY : src/xiaomi.pb-c.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mi-band10-viewer"
	@echo "... src/gb_db.o"
	@echo "... src/gb_db.i"
	@echo "... src/gb_db.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mib10_activity.o"
	@echo "... src/mib10_activity.i"
	@echo "... src/mib10_activity.s"
	@echo "... src/mib10_bluez.o"
	@echo "... src/mib10_bluez.i"
	@echo "... src/mib10_bluez.s"
	@echo "... src/mib10_crypto.o"
	@echo "... src/mib10_crypto.i"
	@echo "... src/mib10_crypto.s"
	@echo "... src/mib10_ui.o"
	@echo "... src/mib10_ui.i"
	@echo "... src/mib10_ui.s"
	@echo "... src/mib10_wire.o"
	@echo "... src/mib10_wire.i"
	@echo "... src/mib10_wire.s"
	@echo "... src/xiaomi.pb-c.o"
	@echo "... src/xiaomi.pb-c.i"
	@echo "... src/xiaomi.pb-c.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

